#!/usr/bin/python

Belgium = 'Belgium,10445852,Brussels,737966,Europe,1830,Euro,Catholicism,Dutch,French,German'
# Ihave made the information into a dictionary
print(Belgium)
location = {
            "Belgium": 10445852,
            "Brussels": 737966,
            "Europe": 1830
           }
print(Belgium.replace(",", ":"))
# keys = location.keys()
# sizel=len(location)
# print(sizel)
# # i made size the input value of the length of belgium
size = len(Belgium)
# # multiplied the input value by the number of sizes
print(size*'-')
# print(location['Belgium'])
# a=location['Belgium']
# print(location['Brussels'])
# b= location['Brussels']

total = int(location.get('Belgium')) + int(location.get('Brussels'))
print(total)
